name: grinn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cudatoolkit=11.8.0
  - intel-openmp=2023.1.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - ncurses=6.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - openssl=3.3.2
  - pdbfixer=1.9
  - pip=24.2
  - python=3.10.15
  - python_abi=3.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - astunparse==1.6.3
      - biopython==1.84
      - cmake==3.30.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - data==0.4
      - decorator==5.1.1
      - et-xmlfile==1.1.0
      - fonttools==4.54.1
      - funcsigs==1.0.2
      - future==1.0.0
      - gmxapi==0.4.2
      - greenlet==3.1.1
      - gromacs==0.0.0
      - gromacswrapper==0.9.1
      - kiwisolver==1.4.7
      - latex==0.7.0
      - matplotlib==3.9.2
      - mda-xdrlib==0.2.0
      - mdtraj==1.10.0
      - mpi4py==4.0.0
      - networkx==3.3
      - numkit==1.3.1
      - openmm==8.1.1
      - openpyxl==3.1.5
      - packaging==24.1
      - pandas==2.2.3
      - panedr==0.8.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - prody==2.5.0
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pybind11==2.13.6
      - pyedr==0.8.0
      - pyparsing==3.1.1
      - pyprind==2.9.8
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - shutilwhich==1.1.0
      - six==1.16.0
      - sqlalchemy==2.0.35
      - tempdir==0.7.1
      - toml==0.10.2
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - utilitylib==2.16
      - xmltodict==0.14.1
